version: 2
jobs:
  test:
    parallelism: 4
    docker:
      - image: circleci/node
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          name: Test application
          command: |
              TEST=$(circleci tests glob **/src/test_*.sh | circleci tests split)
              bash $TEST
workflows:
  version: 2
  test:
    jobs:
      - test